# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
